[[plugins]]
  package = "@sentry/netlify-build-plugin"

  [plugins.inputs]
    sentryOrg = "zenteach"
    sentryProject = "landing"
    deployPreviews = false
    sentryRepository = "https://github.com/ZenTeach/next_zenteach.git"