name: Supabase deploy

on:
  push:
    paths:
      - 'supabase/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
    steps:
      - uses: actions/checkout@v3
      - uses: supabase/setup-cli@v1
        with:
          version: 1.0.0
      - run: supabase functions deploy subscribe  --project-ref $PROJECT_ID
      - run: supabase functions deploy request_demo  --project-ref $PROJECT_ID
      - run: |
          supabase functions deploy hcaptcha_verify  --project-ref $PROJECT_ID
